name: sacredlamb
favicon: null
layout_spectrum: 0.4673
typography_spectrum: 0.82666
title: "Lan-Chi's new website via Grid"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8125
  lightness: 0.8025426755193621
  saturation: 0.25
  rhythmicContrast: 0.6942209703847766
purpose: []
